name: path-filter
on:
  # .github의 workflows안에 part1내에 파일들이 변경될 때 동작
  push:
    paths:
    - '.github/workflows/part1/*'
    - '!.github/workflows/part1/push.yaml' # push.yaml 제외

jobs:
  path-filter:
    runs-on: ubuntu-latest
    steps:
    - name: echo hello
      run: echo hello